### ISSUE TITLE
i call close, get error?

### ISSUE THREAD

**Issue by yuandy** [tsuna/gohbase#112]
My code is:
c := hbase.NewClient("10.65.136.147:2181")
defer c.Close()

But Close get error:
ERRO[0000] error occured, closing region client          client="RegionClient{Addr: hadoop-server-11:16020}" err="client is dead"
ERRO[0000] error occured, closing region client          client="RegionClient{Addr: hadoop-server-10:16020}" err="client is dead"

why?

**Comment by leecha** [comment]
I also met this error, is so big agony! HELP!

**Comment by timoha** [comment]
It's harmless log say that the client got closed. I stopped logging it in latest version.
