### ISSUE TITLE
Why it is so slow compared to any existing Java implementations?

### ISSUE THREAD

**Issue by keyunjie96** [tsuna/gohbase#113]
We compared this library with apache/hbase which is a Java client focused on GET performance. However, we found that even for exactly the same query when rps reaches 3k, the latency of the single "GET" is like seven times longer than apache/hbase.

**Comment by timoha** [comment]
It's likely that with default config of gohbase (optimized for throughput, not latency) you are hitting flush interval every time. Could you try setting https://godoc.org/github.com/tsuna/gohbase#FlushInterval to 0.

**Comment by keyunjie96** [comment]
It works, thanks!
