### ISSUE TITLE
How to scan limit 10 or 100 or other number?

### ISSUE THREAD

**Issue by skyleelove** [tsuna/gohbase#12]
Hi~,
I want to get part of the table, how can i set the limit number?

**Comment by Timoha** [comment]
Take a look at this Scan call, it sets quite a lot of limits: https://github.com/tsuna/gohbase/blob/master/integration_test.go#L548

The translation is: Scan `table` from row `"TestScanTimeRangeVersions1"` to row `"TestScanTimeRangeVersions3"` and for each row return all columns of `"cf"` column family with all versions between `50` and `53` milliseconds. Hope this helps.
