### ISSUE TITLE
ZK root directory /hbase-unsecure

### ISSUE THREAD

**Issue by MonaxGT** [tsuna/gohbase#121]
Hi! 
I tried to use your library and can't find where I can change which path to hbase root directory should use "library". If I understand right default path "/hbase" but we use  "/hbase-unsecure"
How I can change path in your library? 

Thank you!

**Comment by MonaxGT** [comment]
Guys?

**Comment by bingsenmu** [comment]
> Guys?
you can use ZookeeperRoot to rewrite the zkroot from "/hbase" to "/hbase-unsecure", just like:
cli := gohbase.NewAdminClient(*CustomHost, gohbase.ZookeeperRoot("/hbase-unsecure"))
