### ISSUE TITLE
访问hbase效率不高

### ISSUE THREAD

**Issue by nyfooo9** [tsuna/gohbase#138]
Apache的hbase包 有hbase**.thrift文件，根据此文件可生成go的hbase接口，批量读写hbase效率很高

**Comment by codinggg** [comment]
@nyfooo9 你用的是thrift2麽？我用thrift2接口遇到的问题是，在代码里面加filter，结果不起作用。你有遇到这个问题嘛？

**Comment by will2love** [comment]
> @nyfooo9 你用的是thrift2麽？我用thrift2接口遇到的问题是，在代码里面加filter，结果不起作用。你有遇到这个问题嘛？

可以发出来看看 我好像用scan可以的

**Comment by 89trillion-wenjie** [comment]
> @nyfooo9 你用的是thrift2麽？我用thrift2接口遇到的问题是，在代码里面加filter，结果不起作用。你有遇到这个问题嘛？

老哥 请问你这个问题解决了吗 我也是thrift2加filter不起作用
但是thrift(1)加filter是正常的 这是怎么回事啊
