### ISSUE TITLE
Reference to undefined identifiers : runtime.RaceAcquire, runtime.RaceReleaseMerge, runtime.RaceReadRange, runtime.RaceWriteRange

### ISSUE THREAD

**Issue by advancedwebdeveloper** [tsuna/gohbase#151]
Hi.
Can't run your tests:

> $ make test
> go test -v -race -timeout=30s ./...
> # github.com/tsuna/gohbase
> package testmain: cannot find package
> FAIL	github.com/tsuna/gohbase [setup failed]
> # github.com/tsuna/gohbase/compression/snappy
> package testmain: cannot find package
> FAIL	github.com/tsuna/gohbase/compression/snappy [setup failed]
> # github.com/tsuna/gohbase/hrpc
> package testmain: cannot find package
> FAIL	github.com/tsuna/gohbase/hrpc [setup failed]
> # github.com/tsuna/gohbase/region
> package testmain: cannot find package
> FAIL	github.com/tsuna/gohbase/region [setup failed]
> # github.com/tsuna/gohbase/test/mock
> package testmain: cannot find package
> FAIL	github.com/tsuna/gohbase/test/mock [setup failed]
> ?   	github.com/tsuna/gohbase/compression	[no test files]
> # golang.org/x/sys/unix
> ../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/race.go:17:10: error: reference to undefined identifier 'runtime.RaceAcquire'
> ../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/race.go:21:10: error: reference to undefined identifier 'runtime.RaceReleaseMerge'
> ../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/race.go:25:10: error: reference to undefined identifier 'runtime.RaceReadRange'
> ../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/race.go:29:10: error: reference to undefined identifier 'runtime.RaceWriteRange'
> ?   	github.com/tsuna/gohbase/filter	[no test files]
> ?   	github.com/tsuna/gohbase/pb	[no test files]
> ?   	github.com/tsuna/gohbase/test	[no test files]
> ?   	github.com/tsuna/gohbase/test/mock/region	[no test files]
> make: *** [Makefile:32: test] Error 2
> 
.

@ianlancetaylor , could you elaborate regarding unix/race.go ? Any suggestion on what could the cause?

CC @thanm @cherrymui

Ivan

**Comment by ianlancetaylor** [comment]
Are you still using GoLLVM?  You didn't say.

gccgo and GoLLVM do not support the race detector.  The `-race` flag does not work for those compilers.
