### ISSUE TITLE
Does this client support hbase version >= 2.2.0 or newer ?

### ISSUE THREAD

**Issue by DavidLiRemini** [tsuna/gohbase#179]
I found  the ***.proto*** pb protocol is based on hbase-1.3.0 version, but my hbase version is 2.2.0, I'm not sure if there are some subtle differences
plz enlighten me

**Comment by dethi** [comment]
We aims to support as much version as possible (HBase >= 1.0.0), so 2.2.0 should work.

Currently our CI runs against 2.4.8 ( https://github.com/tsuna/gohbase/blob/master/.github/workflows/ci.yml#L17)

**Comment by DavidLiRemini** [comment]
Thanks for the explanation

> We aims to support as much version as possible (HBase >= 1.0.0), so 2.2.0 should work.
> 
> Currently our CI runs against 2.4.8 ( https://github.com/tsuna/gohbase/blob/master/.github/workflows/ci.yml#L17)
