### ISSUE TITLE
stuck in an infinite loop in lookupRegion function

### ISSUE THREAD

**Issue by LG991103** [tsuna/gohbase#189]
i can't connect our hbase cluster 
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/51302760/173051009-206d988a-e65d-4a72-9466-59690fc3691e.png">
I was expecting to exit with an error after 10 retries, but I've been looping infinitely in the lookupRegion method and I can't exit. The reason is because the timeout error of the context is overwritten by the sleepAndIncreaseBackoff method, causing the err to become nil, forming an infinite loop
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/51302760/173051601-1ed91355-3fb3-4f26-9f1c-16b52b423699.png">

**Comment by LG991103** [comment]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/51302760/173096870-81d2927c-8242-4b2e-a1ba-a82a66ef1edc.png">

**Comment by dethi** [comment]
Indeed there is 2 levels of retries here. The first one `getRegionForRpc` that will try 10 times and the second one in `lookupRegion` that just exponentially retry forever. They do have different purpose. I will have to dig more.

**Comment by timoha** [comment]
@LG991103 you have to use context with deadine/timeout if you want your requests to exit without retrying forever. It's not stuck, the default behavior is to retry forever until the request goes through to regionserver (it becomes available and starts accepting the requests for that region you are trying to send to).

The 10 times retry is only for unrecoverable cases where we can't determine which region to send the request to. So maybe zookeeper missing the state, or maybe master is down and haven't updated zookeeper for a while. Pretty much if you are getting ErrCannotFindRegion, hbase operator needs to go in an see if everything is healthy with the cluster.
