### ISSUE TITLE
client error

### ISSUE THREAD

**Issue by XieWeiXie** [tsuna/gohbase#192]
ERRO[0030] failed looking up region                      backoff=16ms err="context deadline exceeded" key="\"300605_1658758250_abce\"" table="\"student\""

DEBU[0001] region was not established, retrying          backoff=1.024s err="region.NotServingRegionError: HBase Java exception org.apache.hadoop.hbase.NotServingRegionException:\norg.apache.hadoop.hbase.NotServingRegionException: Region hbase:meta,,1 is not online on hbase-regionserver-1,16020,1658850222232\n\tat org.apache.hadoop.hbase.regionserver.HRegionServer.getRegionByEncodedName(HRegionServer.java:2942)\n\tat org.apache.hadoop.hbase.regionserver.RSRpcServices.getRegion(RSRpcServices.java:1072)\n\tat org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2026)\n\tat org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:33644)\n\tat org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2196)\n\tat org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)\n\tat org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)\n\tat org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)\n\tat java.lang.Thread.run(Thread.java:748)\n" region="RegionInfo{Name: \"hbase:meta,,1\", ID: 0, Namespace: \"hbase\", Table: \"meta\", StartKey: \"\", StopKey: \"\"}"

/etc/hosts   done

hbase shell done

what is problem?

**Comment by dethi** [comment]
> what is problem?
```
Region hbase:meta,,1 is not online on hbase-regionserver-1,16020,1658850222232
```

**Comment by YaoKongxuan** [comment]
hi do you know the reason？

**Comment by dethi** [comment]
This is a problem with your HBase cluster that I can't solve. `gohbase` is just telling you that HBasemaster told it that the `hbase:meta` region is on `hbase-regionserver-1` but it either wasn't able to reach `hbase-regionserver-1` or `hbase-regionserver-1` responded that it doesn't have that region open.

**Comment by YaoKongxuan** [comment]
thx
