### ISSUE TITLE
Bump go.mod go version to go1.18?

### ISSUE THREAD

**Issue by dethi** [tsuna/gohbase#204]
Golang officially only support the [last 2 major versions](https://go.dev/doc/devel/release). Bumping to 1.18 would allow us to update a bunch of dependency (see my failed attempt https://github.com/tsuna/gohbase/pull/203) and also use generics. I can see one area where it could be nice to have: the regions cache.

Opinions?

**Comment by aaronbee** [comment]
I don't see why not.
