### ISSUE TITLE
batch operation support ？

### ISSUE THREAD

**Issue by similove** [tsuna/gohbase#206]
Hi~

Current version support batch get, batch delete and bacth put ? Consider performance, and less RPC calls ?

**Comment by dethi** [comment]
gohbase already batch requests internally. This can be configured via the [RPCQueueSize](https://github.com/tsuna/gohbase/blob/master/client.go#L209) and [FlushInterval](https://github.com/tsuna/gohbase/blob/master/client.go#L252). See default [here](https://github.com/tsuna/gohbase/blob/master/client.go#L26).

Exposing the batching API to the caller is a request tracked via https://github.com/tsuna/gohbase/issues/68, and recent work has started to fulfil that request https://github.com/tsuna/gohbase/pull/202
