### ISSUE TITLE
Why is Scan operation stuck for ~1s every X records retrieved? And How to disable logger?

### ISSUE THREAD

**Issue by JobberRT** [tsuna/gohbase#207]
I have 100K~300K hbase records and I found that using `gohbase`'s `Scan` method, it will stuck for abound 1s every nearly 1~3s, causing retrieving data slow. Is this a problem with `FlushInterval` or `RpcQueueSize`? I've set interval to 0 and queue size to 10000(also tried other value, but no change was happened).

And also, how to disable the `logrus` logger? I think as a library, you should pass the error to user and let them handle, other than logging the error yourself

**Comment by dethi** [comment]
At the moment, there isn't any way to disable the logger only for gohbase. We use the default logger, so you could use `logrus.SetOutput(io.Discard)` or change the log level. Errors are not logged if unhandled. We only logs debug and info level information that are useful to understand the behaviour of the client.

Ideally, we would let the caller configure the logger used by the client. Open to contribution to make that change.

**Comment by dethi** [comment]
As for your original question, we would need a little bit more details. Like what does your scan looks like? Can you provide a dataset to reproduce? What's the size of the cluster? Have you verified that the scanner request isn't waiting in a HBase queue to be processed? Etc

**Comment by JobberRT** [comment]
@dethi Thanks for replying, the logging thing is no a big deal. For the original question, here's more detail:
1. I'm using `hrpc.NewScanRange` to set a `startRowPrefix` and set a `hrpc.Families` filter to it.(Since I see `filter.XXXFilter` especially `filter.RowPrefixFilter` are **TODO**)
2. Same cluster with same scan(same familiy filter and same row prefix) in apache's java client, it has some latency as well but latency is much lower to human eyes.


I guess this maybe some kind of buffering issue? Once buffer is full it needs to flush/reset to receive next data? I will dig into it. For now, since java client also has this behivor though with a much lower latency, I think this is not `gohbase` issue. So I will close this issue

**Comment by dethi** [comment]
Ok 👍🏻
