### ISSUE TITLE
Console gets stuck, doesn't print anything.

### ISSUE THREAD

**Issue by tferreirap** [tsuna/gohbase#22]
Hi there,

I'm really new at using hbase and I think this library would be of great help. Unfortunately I can't get any response from its methods. Every time I run something the console get stuck and stop printing. For instance, this is my code below:

```go
package main

import (
	"fmt"
	"github.com/tsuna/gohbase"
	"github.com/tsuna/gohbase/hrpc"
	"golang.org/x/net/context"
)

func main() {

	client := gohbase.NewClient("localhost:8080")

	fmt.Printf("1\n")

	getRequest, err := hrpc.NewGetStr(context.Background(), "mytable", "row1")

        if err != nil {
		fmt.Printf("Error: %s", err)
	}

	fmt.Printf("2\n")

	getRsp, err := client.Get(getRequest)
	fmt.Printf("3\n")
	fmt.Println(getRsp)

	scanRequest, err := hrpc.NewScanStr(context.Background(), "mytable")

	if err != nil {
		fmt.Printf("Error: %s", err)
	}

	rsp, err := client.Scan(scanRequest)
	
	if err != nil {
		fmt.Printf("error: %v", err)
	}

	if len(rsp) != 1 {
		fmt.Printf(" %s rows", len(rsp))
	}

	fmt.Printf("-- ENDED -- ")
}
```

Few notes: 

- When I run this it prints 1 and 2, then it get stucks in the **client.Get()** (same thing would happen with NewScanStr() ) 
- I know that my hbase is working fine because I'm able to insert rows and use scanners using curl.
- Sorry if it seems like a noob question, I couldn't find any other tutorials online :)

Does someone have any idea of what is going on?

**Comment by Timoha** [comment]
`localhost:8080` are you sure that you hbase is running on 8080? seems like an odd port for it to run on

**Comment by Timoha** [comment]
Has this been resolved, can I close this issue?
