### ISSUE TITLE
zookeeper连接时间为什么是30秒？  对于web服务来说是不是太长了？

### ISSUE THREAD

**Issue by quven1990** [tsuna/gohbase#221]
https://github.com/tsuna/gohbase/blob/f15274ad1309fea37510457a85ddd0a15d79de35/client.go L29

**Comment by dethi** [comment]
This is just the default value for the Zookeeper client. Gohbase use Zookeeper only to find the location of the meta table and for other admin operation (when using the admin client).

You can customise the timeout if needed using: https://github.com/tsuna/gohbase/blob/f15274ad1309fea37510457a85ddd0a15d79de35/client.go#L225

For example:
```go
gohbase.NewClient("localhost:3100", gohbase.ZookeeperTimeout(5*time.Second))
```

**Comment by dethi** [comment]
Don't hesitate to re-open if that doesn't answer your question!
