### ISSUE TITLE
How do I know a scan result is returned due to MaxResultSize limit?

### ISSUE THREAD

**Issue by shortsteel** [tsuna/gohbase#224]
Hi all, this SDK has ben incredible in terms of compatibility, performance and usability and has been a great help in my project! Thanks for your amazing work!

I do have a question concerning `MaxResultSize` maybe you can help explain:

With the Scan operation, sometime I can't get all the rows I want in one request due to the MaxResultSize limit, but there is no way (to the best of my knowledge) to know whether a scan result is returned because of MaxResultSize or due to reach of MaxResultSize. 

My current approach is to add additional scans following the initial scan, using the last RowKey of the initial scan result as Start Row, to ensure I've got all the rows I specified in my Range. This means I would need at least 2 scan calls to finish a Range Scan.

Is there a better way to fetch all the rows in my Scan Range instead of doing so such extra scan calls?

**Comment by shortsteel** [comment]
Thank you @dethi for your reply! It turns out to be a compatibility issue with our cloud service provider (thier version of hbase somehow behaves differently than the official hbase distribution)

**Comment by dethi** [comment]
Oh interesting. Do you mind sharing the name of the cloud service you use?
