### ISSUE TITLE
Version is too high

### ISSUE THREAD

**Issue by boruns** [tsuna/gohbase#236]
Does it depend on a lower version of go? The current version 1.18 is too high for my project and I cannot use it.

**Comment by boruns** [comment]
my version is 1.15。

**Comment by dethi** [comment]
One of dependencies use generic, so no 1.18 is the minimum version required right now. In general, like most Go library maintainers, we only aim to support the officially supported Go versions, i.e. `Each major Go release is supported until there are two newer major releases` [1].

If you absolutely don't care about bug fixes, you can use any gohbase commits prior to [this commit](https://github.com/tsuna/gohbase/commit/7b0ead0932effeda8ecd0ec78fc885abb0debb67).

[1] https://go.dev/doc/devel/release
