### ISSUE TITLE
Scan doesn't work across regions, doesn't respect numberOfRows filter

### ISSUE THREAD

**Issue by ipostelnik** [tsuna/gohbase#27]
We've fixed it on our fork here - https://github.com/cloudflare/gohbase/pull/8. What is the current way to submit PRs?

**Comment by Timoha** [comment]
Thank you for reporting it, I'll try to reproduce it.

> What is the current way to submit PRs?

Checkout this section of the README: https://github.com/tsuna/gohbase#contributing

**Comment by ipostelnik** [comment]
I'm having trouble pushing to gerrit because the master branch is way out of date.

**Comment by ipostelnik** [comment]
FWIW, the core bug is `:=` on line 117 of client.go shadowing `rpc` variable on so the check above always see the version of the variable from the parent scope, which remains `nil`.

**Comment by Timoha** [comment]
> I'm having trouble pushing to gerrit because the master branch is way out of date.

sorry about that, I asked @tsuna to let me update it

> FWIW, the core bug is := on line 117 of client.go shadowing rpc variable, so the check above always see the version of the variable from the parent scope, which remains nil.

right, we took a look at that, and it looks legit.

**Comment by Timoha** [comment]
Hello,

So we decided to dump using GerritHub in favor just Pull requests. Feel free to send a Pull request with changes, make sure to sign (Contributor Licensing Agreement)[https://docs.google.com/forms/d/e/1FAIpQLSezRIx_GaGhT_4uwXUpa7xgL4hdB6rlVDYt9KEc-Gd9lQWwXw/viewform?formkey=dFNiOFROLXJBbFBmMkQtb1hNMWhUUnc6MQ] first if you haven't done so yet.
