### ISSUE TITLE
`zkRoot` is not set to `defaultZkRoot` for `AdminClient`

### ISSUE THREAD

**Issue by Timoha** [tsuna/gohbase#33]
@jonbonazza Looks like there's a bug introduced by #32 where it was forgotten to set `zkRoot` in `AdminClient` https://github.com/tsuna/gohbase/blob/master/admin_client.go#L36 which broke operations on hbase master.

**Comment by jonbonazza** [comment]
Odd... I specifically remember adding this line in... Perhaps i forgot to add the file to the commit?  Would you like me to fix it real fast or are you already on it?

**Comment by Timoha** [comment]
yeah, if you don't mind

**Comment by jonbonazza** [comment]
I'm working on it now. I'm on a different laptop so gimme a bit to check everything out again.

**Comment by jonbonazza** [comment]
fixed in #34

**Comment by jonbonazza** [comment]
Major apologies for that.

**Comment by Timoha** [comment]
no worries, thanks for a super quick response!

**Comment by jonbonazza** [comment]
Least I could do after breaking master! :)

**Comment by jonbonazza** [comment]
Least I could do after breaking master! :)
