### ISSUE TITLE
How to use Scan?

### ISSUE THREAD

**Issue by LaughingVzr** [tsuna/gohbase#45]
I got the scan demo and try it,but got this log.
`ERRO[0060] failed looking up region                      backoff=32ms err="deadline exceeded" key= table=QueryCompHtableName`

can u show a detail scan demo?
Thank U.

**Comment by Timoha** [comment]
Hello,
You can check an example on how to use `Scan` in our [integration tests](https://github.com/tsuna/gohbase/blob/master/integration_test.go#L605). The documentation for `Scanner` is [here](https://godoc.org/github.com/tsuna/gohbase/hrpc#Scanner).

Hope this helps.
