### ISSUE TITLE
Coprocessor client

### ISSUE THREAD

**Issue by leoyer** [tsuna/gohbase#47]
If my hbase has a custom Coprocessor, I can like SCANNER to achieve a communication with the custom Coprocessor Client ? Or is the project already having such a function?

**Comment by Timoha** [comment]
yes, please feel free to implement whatever you need. gohbase doesn't have any functionality for custom coprocessor at the moment.

You might need to look at adding new hrpc.Call type that creates this request: https://github.com/tsuna/gohbase/blob/master/pb/Client.pb.go#L1175

**Comment by leoyer** [comment]
ok , thinks

**Comment by leoyer** [comment]
我扩展了源码,使之很容易请求并获取自定义corprocessor.我把代码贴出来也许可以帮到有同样需求的人

hrpc/corprocessor.go
`package hrpc

import (
	"github.com/tsuna/gohbase/pb"
	"github.com/golang/protobuf/proto"
	"context"
	"github.com/tsuna/gohbase/filter"
)

type Coprocessor struct {
	base
	corRquest ServiceRequest
}

func baseCoprocessor(ctx context.Context, table []byte,request ServiceRequest,
	options ...func(Call) error) (*Coprocessor, error) {
	s := &Coprocessor{
		base: base{
			table: table,
			ctx:   ctx,
		},
		corRquest:request,
	}
	err := applyOptions(s, options...)
	if err != nil {
		return nil, err
	}

	return s, nil
}

func NewCoprocessor(ctx context.Context, table string,request ServiceRequest, options ...func(Call) error)(*Coprocessor, error){
	return baseCoprocessor(ctx,[]byte(table),request,options... )
}

type CoprocessorIte interface {

	Next() (ServiceResponse, error)

	Close() error
}

type ServiceRequest interface{
	GetServiceName() string
	GetMethodName() string
	GetRow() []byte
	GetProtoRequest() ([]byte,error)
}
type ServiceResponse interface{
	GetResponse(responseByte []byte) ServiceResponse
}





// Name returns the name of this RPC call.
func (s *Coprocessor) Name() string {
	return "ExecService"
}

// ToProto converts this Scan into a protobuf message
func (s *Coprocessor) ToProto() (proto.Message, error) {
	coprocessor := &pb.CoprocessorServiceRequest{
		Region:       s.regionSpecifier(),
		Call: &pb.CoprocessorServiceCall{},
	}
	coprocessor.Call.Row = s.corRquest.GetRow()
	serviceName := s.corRquest.GetServiceName()
	coprocessor.Call.ServiceName = &serviceName
	methodName := s.corRquest.GetMethodName()
	coprocessor.Call.MethodName = &methodName
	if  requstBytes,err :=  s.corRquest.GetProtoRequest(); err == nil{
		coprocessor.Call.Request = requstBytes
	}else{
		return nil, err
	}
	return coprocessor, nil
}

// NewResponse creates an empty protobuf message to read the response
// of this RPC.
func (s *Coprocessor) NewResponse() proto.Message {
	return &pb.CoprocessorServiceResponse{}
}

// SetFamilies sets the families covered by this scanner.
func (s *Coprocessor) SetFamilies(fam map[string][]string) error {
	return nil
}

// SetFilter sets the request's filter.
func (s *Coprocessor) SetFilter(ft filter.Filter) error {
	return nil
}


// SetFilter sets the request's filter.
func (s *Coprocessor) GetCorRequest() ServiceRequest {
	return s.corRquest
}


// SetFilter sets the request's filter.
func (s *Coprocessor) SetCorRequest(request ServiceRequest) error {
	s.corRquest = request
	return nil
}`

corprocessor_ite.go

`package gohbase

import (
	"github.com/tsuna/gohbase/hrpc"
	"sync"
	"context"
	"io"
	"github.com/tsuna/gohbase/pb"
	"errors"
)

type coprocessorRe struct{
	r hrpc.ServiceResponse
	e error
}


type coprocessorIte struct {
	// fetcher's fileds shouldn't be accessed by scanner
	// TODO: maybe separate fetcher into a different package
	f       coprocessorFetcher
	once    sync.Once
	results chan coprocessorRe
	cancel  context.CancelFunc
}

func newCoprocessorIte(c RPCClient, rpc *hrpc.Coprocessor,result hrpc.ServiceResponse) *coprocessorIte {
	ctx, cancel := context.WithCancel(rpc.Context())
	results := make(chan coprocessorRe)
	return &coprocessorIte{
		results: results,
		cancel:  cancel,
		f: coprocessorFetcher{
			RPCClient: c,
			rpc:       rpc,
			ctx:       ctx,
			results:   results,
			result:result,
		},
	}
}


func (s *coprocessorIte) Next() (hrpc.ServiceResponse, error) {
	s.once.Do(func() {
		go s.f.fetch()
	})

	re, ok := <-s.results
	if !ok {
		return nil, io.EOF
	}
	return re.r, re.e
}

func (s *coprocessorIte) Close() error {
	s.cancel()
	return nil
}

type coprocessorFetcher struct {
	RPCClient
	results chan<- coprocessorRe
	// rpc is original scan query
	rpc *hrpc.Coprocessor
	ctx context.Context
	// result current result we are adding partials to
	result hrpc.ServiceResponse
}



// send sends a result and error to results channel. Returns true if scanner is done.
func (f *coprocessorFetcher) send(r *pb.CoprocessorServiceResponse, err error) bool {
	if r == nil {
		if err == nil {
			// nothing to be sent yet
			return false
		}
	}

	return f.trySend( f.result.GetResponse(r.Value.Value) , err)
}

func (f *coprocessorFetcher) trySend(r hrpc.ServiceResponse, err error) bool {
	select {
	case <-f.ctx.Done():
		return true
	case f.results <- coprocessorRe{r: r, e: err}:
		return false
	}
}

// fetch scans results from appropriate region, sends them to client and updates
// the fetcher for the next scan
func (f *coprocessorFetcher) fetch() {
	for {
		resp, region, err := f.next()
		if err != nil {
			if err != ErrDeadline {
				// if the context of the scan rpc wasn't cancelled (same as calling Close()),
				// return the error to client
				f.send(nil, err)
			}
			break
		}
		f.send(resp,nil )

		// check whether we should close the scanner before making next request
		if f.shouldClose(resp, region) {
			/*if f.result != nil {
				// if there were results, send the last row
				f.trySend(f.result, nil)
			}*/
			break
		}
	}

	close(f.results)
}

func (f *coprocessorFetcher) next() (*pb.CoprocessorServiceResponse, hrpc.RegionInfo, error) {
	var rpc *hrpc.Coprocessor
	var err error

	rpc,err  = hrpc.NewCoprocessor(f.ctx, string(f.rpc.Table()), f.rpc.GetCorRequest())

	res, err := f.SendRPC(rpc)
	if err != nil {
		return nil, nil, err
	}
	coprocessors, ok := res.(*pb.CoprocessorServiceResponse)
	if !ok {
		return nil, nil, errors.New("got non-ScanResponse for scan request")
	}
	return coprocessors, rpc.Region(), nil
}
// shouldClose check if this scanner should be closed and should stop fetching new results
func (f *coprocessorFetcher) shouldClose(resp *pb.CoprocessorServiceResponse, region hrpc.RegionInfo) bool {
	select {
	case <-f.ctx.Done():
		// scanner has been asked to close
		return true
	default:
	}
	if len(region.StopKey()) == 0 {
		return true
	}
	// (3) because its stop_key is greater than or equal to the stop_key of this scanner,
	// provided that (2) we're not trying to scan until the end of the table.
	return false
}`

extend_client.go
`package gohbase

import (
	"github.com/tsuna/gohbase/hrpc"
)

type ExtendClient interface{
	Client
	ExecService(request *hrpc.Coprocessor,response hrpc.ServiceResponse) hrpc.CoprocessorIte
}


type extendClient struct {
	*client
}

// NewClient creates a new HBase client.
func NewExtendClient(zkquorum string, options ...Option) ExtendClient {
	return  &extendClient{
		client:newClient(zkquorum, options...),
	}
}



func (c *extendClient) ExecService(request *hrpc.Coprocessor,response hrpc.ServiceResponse) hrpc.CoprocessorIte {
	return newCoprocessorIte(c,request,response)
}`


Example:
I have a custom corprocessor and the proto is follow
countServer.proto
`
package protob;
option java_package = "com.bwdz.coprocessor.endpoint.count";
import "params.proto";
option java_outer_classname = "CountServer";
option java_generic_services = true;
option java_generate_equals_and_hash = true;
option optimize_for = SPEED;

message CountRequest {
  required string startKey = 1;
  required string endKey = 2;
  repeated Params params = 3;
  required string column = 4;
  optional string defaultQualifier = 5;
}

message CountResponse {
  required int64 count = 1 [default = 0];
}

service Count {
  rpc sendCountRequest(CountRequest)
    returns (CountResponse);

}
`

1.  use protobuf generate go file
2.  create request ,response  implements ServiceRequest/ServiceResponse for the proto file Obj
count_service.go
`
package corpro

import (
	"zrsf.com/hquery/protob"
	"github.com/tsuna/gohbase/hrpc"
	"github.com/golang/protobuf/proto"
)

type CountServiceResponse struct {
	Count int64
}

func (c *CountServiceResponse) GetResponse(responseByte []byte) hrpc.ServiceResponse {
	res := protob.CountResponse{}
	rsp := &CountServiceResponse{
	}
	if err := proto.Unmarshal(responseByte,&res);err== nil{
		rsp.Count = *res.Count
		return rsp
	}
	return nil
}

func NewCountServiceResponse() *CountServiceResponse{
	return  &CountServiceResponse{}
}



type countServiceRequest struct {
	startKey   string
	endKey           string
	params           []*Params
	column           string
	defaultQualifier string
}

func NewCountServiceRequest(start ,end ,family,defaultQualifier  string , params    []*Params) *countServiceRequest{
	return  &countServiceRequest{
		startKey:start,
		endKey:end,
		params:params,
		column:family,
		defaultQualifier:defaultQualifier,
	}
}

// Name returns the name of this RPC call.
func (s *countServiceRequest) GetServiceName() string {
	return "Count"
}


func (s *countServiceRequest) GetMethodName() string {
	return "sendCountRequest"
}

func (s *countServiceRequest) GetRow() []byte{
	return []byte(s.startKey)
}

func (s *countServiceRequest) GetProtoRequest() ([]byte,error) {
	var cusParams []*protob.Params
	for _,param := range s.params{
		pa := &protob.Params{
			Key: &(param.Key),
			Value: &(param.Value),
			Type: &(param.Type),
		}
		cusParams = append(cusParams,pa)
	}
	requstMessage := protob.CountRequest{
		StartKey:&s.startKey,
		EndKey:&s.endKey,
		Params:cusParams,
		Column:&s.column,
		DefaultQualifier:&s.defaultQualifier,
	}

	return proto.Marshal(&requstMessage)
}


`

3. use the coprocessor like scan
`
countRequest := corpro.NewCountServiceRequest(
		"000000000000000000001607220002340012321933","99999999999999999999999999999999999999999",
		"DATA","JSHJ",nil,
	)
	corp,err := hrpc.NewCoprocessor(context.Background(),"KPF_INDEX",countRequest)
	if err == nil{
		resp := corpro.NewCountServiceResponse()
		ite := util.GetHbaseClient().ExecService(corp,resp)
		result ,err :=   ite.Next()
		for ( err != io.EOF){
			if coutRes, ok :=  result.(*corpro.CountServiceResponse);ok{
				println("ssss",coutRes.Count )
			}
			result ,err  =   ite.Next()
		}

	}
`
