### ISSUE TITLE
How to support hbase verison 0.98 0.96 or others below 1.0

### ISSUE THREAD

**Issue by chennqqi** [tsuna/gohbase#48]
plz give me some ideas

**Comment by Timoha** [comment]
Unfortunately that's not possible with this client as it was started with supporting >= 1.0.0 in mind. Difference in how you talk to hbase < 1.0.0  and >= 1.0.0 work is pretty drastic, and I don't think it's worth the effort to support 2+ year old versions.

**Comment by tsuna** [comment]
Please upgrade past HBase 1.0, it is not recommended to run these obsolete versions of HBase anymore.

**Comment by chennqqi** [comment]
@tsuna I prefer to upgrade Hbase1.0. But the whole corp's hbase cluster build on 0.96, it's not easy to do this. And The Operation and maintenance department won't take this advice. So i have to find a way...
