### ISSUE TITLE
Infinite loop looking up regions

### ISSUE THREAD

**Issue by dougklein** [tsuna/gohbase#49]
Hello,

I've been using this library for a while and I've just updated the latest version. I am having problems with an infinite loop looking up regions. I've tried this with HBase 1.2.4 and 1.3.1 - both on a large cluster and on my local machine with the same results.  It works fine simply recompiling with the older version. Any ideas? 

go version go1.8 linux/amd64

hbase

create 'doug','c'
put 'doug','boo','c:hoo',':-('

----------------
main.go
----------------

package main 

import (
	"context"
	"log"
	"github.com/tsuna/gohbase"
	"github.com/tsuna/gohbase/hrpc" ) 

func main() {

	client := gohbase.NewClient("localhost")
	getRequest, err := hrpc.NewGetStr(context.Background(), "doug", "boo")
	if err != nil {
		log.Printf("%s", err.Error())
	}
	getRsp, err := client.Get(getRequest)
	log.Printf("found results %v", getRsp)

}

**Comment by Timoha** [comment]
Hello @dougklein, thanks for reporting, this is a know issue, I'm looking into it.

**Comment by Timoha** [comment]
Actually, you are probably hitting a different issue as I wasn't able to reproduce the infinite loop with the code you provided. Could you add `logrus.SetLevel(logrus.DebugLevel)` before creating the client and post your output here. Thanks!

**Comment by dougklein** [comment]
Here you are - debug level with the working library and not latest one.
[works.txt](https://github.com/tsuna/gohbase/files/1084294/works.txt)

[notworks.txt](https://github.com/tsuna/gohbase/files/1084295/notworks.txt)

**Comment by Timoha** [comment]
Ok, I think I was able to reproduce the issue you are seeing. Looks the version of https://github.com/cznic/b you have (dependency of gohbase) is out of date. There was a [fix](https://github.com/cznic/b/commit/aaaa43c92e509a827e63540510bc94c3003ef2e1) for the Prev() method without which I'm seeing the same notworks output as you are. Can you try updating that library to confirm that this is the issue?

**Comment by dougklein** [comment]
That fixes the problem. Thank you! 

Will of course let you know if we run into other issues.

- Doug
