### ISSUE TITLE
Implement Multiactions

### ISSUE THREAD

**Issue by Lazyshot** [tsuna/gohbase#5]
Allow a user to send multiple actions in one call. 

This requires grouping actions by region (rowKey) and using the MultiRequest, RegionAction, and Action protobuf message types.

**Comment by timoha** [comment]
done with this commit: https://github.com/tsuna/gohbase/commit/1cb47d737ef4b0481338d44e5a3c68715ca6cb04

The batching is handled by gohbase internally.
