### ISSUE TITLE
Implement Truncate

### ISSUE THREAD

**Issue by jonbonazza** [tsuna/gohbase#59]
There is no protocol command to do this, so it would need to be implemented by combining disable + drop + create. I have implemented this myself in a wrapper, and it works, but there are two issues that would be best if directly integrated into gobhase:
1. The largest issue is that with the current API exposed by gohbase, you need to specify the column families when you create the table, and if a table already exists, there is no way to retrieve this information. For this to work best, gohbase should at least implement the Describe Table command to retrieve this information programmatically.
2. Disable, Drop, and Create all take a context.Context, which is great, but there is no easy way (that I am aware of, at least) to have a context that spans all 3 of these commands. For instance, If I pass a context to the Truncate function, it should only call Done when all 3 of Disable, Drop, and Create have completed.

It would be nice if gohbase provided this integration directly. At the _very_ least, support for Describe Table would be great.

**Comment by timoha** [comment]
I would prefer to implement the support for DescribeTable and keep AdminClient to minimum. It should be trivial to implement Truncate by users. We can start from that at least.

**Comment by jonbonazza** [comment]
Implementing DescribeTable is a great start, but leaving implementation of Truncate up to the user leaves issue #2 unresolved. Unless you can think of a better way to handle the cross-call context for cancellation?

**Comment by jonbonazza** [comment]
Actually, I think my understanding of ```context.Context``` was inaccurate and this _should_ just work.

**Comment by jonbonazza** [comment]
I'm going to close this for now.
