### ISSUE TITLE
kerberos support?

### ISSUE THREAD

**Issue by chy373** [tsuna/gohbase#71]
how can I work with a hbase cluster with kerberos?

**Comment by niklausxiao** [comment]
seems no kerberos support yet.

I searched lots of golang implementation of hadoop client, include hdfs,yarn, hbase, kafka, none of them support kerberos. :(

**Comment by timoha** [comment]
gohbase doesn't support any authentication methods at the moment as we haven't had a need for it ourselves. If you think this could be useful and are interested to help out, you are welcome to send a PR
