### ISSUE TITLE
Create Table with Region Number

### ISSUE THREAD

**Issue by alpancs** [tsuna/gohbase#76]
How can I create table like this query in gohbase?
`create 't1', 'f1', {NUMREGIONS => 15, SPLITALGO => 'HexStringSplit'}`

**Comment by timoha** [comment]
You can do this with SplitKeys during CreateTable: https://godoc.org/github.com/tsuna/gohbase/hrpc#SplitKeys
Checkout an example in tests: https://github.com/tsuna/gohbase/blob/master/table_test.go#L72

**Comment by alpancs** [comment]
thanks @timoha :+1:
