### ISSUE TITLE
NumberOfRows option has no effect.

### ISSUE THREAD

**Issue by Bren2010** [tsuna/gohbase#77]
The NumberOfRows option on a scan has no effect. It is ignored internally.

**Comment by timoha** [comment]
Could you provide more information. Version of hbase, code snippet, what you expect happen, etc. We have tests for this case, and it's strange you are running into this.

**Comment by Bren2010** [comment]
I have a use-case where I do many short scans, and I realized that despite setting `NumberOfRows` to 5 the scans were still very slow in a large table. Looking at master, `func NumberOfRows` sets a `numberOfRows` field on a `Scan`. However the field `numberOfRows` is only consumed by the `Scan.String` method. If I override line 191 in hrpc/scan.go (in method `Scan.ToProto`), the scans become fast again.

**Comment by timoha** [comment]
My bad, you are completely right, I'll send a fix soon. Seems like our tests are wrong then.
