### ISSUE TITLE
There is always a dead client error when I try to close all clients before the process exited

### ISSUE THREAD

**Issue by caesarjuly** [tsuna/gohbase#78]
The error is listed below.
`ERRO[0035] error occured, closing region client          client="RegionClient{Addr: xxxxx:xxx}" err="client is dead"`

Is this normal? After several seconds, the process exited successfully.

**Comment by zuston** [comment]
i meet the same problem

**Comment by timoha** [comment]
It's a harmless error, it just happens that gohbase logs it as an error. `client is dead` because you closed it.

**Comment by DandyDev** [comment]
If it's harmless, then why does gohbase log it as an error? These "harmless" log messages show up in client applications that use gohbase, and the only way to get rid of them is to disable logging altogether.

I recommend not logging at all btw. gohbase is a library, and as such should communicate failure to consuming code by returning errors from function calls.
