### ISSUE TITLE
Delete rows with a specified timestamp

### ISSUE THREAD

**Issue by yinthewind** [tsuna/gohbase#79]
It seems to me gohbase doesn't support delete row actions with a specified timestamp: 
https://github.com/tsuna/gohbase/blob/bfd7afa1423fbdec124e8b773501df9a421dc2cd/hrpc/mutate.go#L241

Is that correct?

**Comment by timoha** [comment]
it's supported: https://godoc.org/github.com/tsuna/gohbase/hrpc#NewDelStr
