### ISSUE TITLE
Goroutine-safe?

### ISSUE THREAD

**Issue by Taik** [tsuna/gohbase#8]
Hello,

I'm currently using this library to do write kafka events into HBase. After skimming the code, there's a few questions that I hope you can help clarify for me.

* Is the libary thread safe? Looking at https://github.com/tsuna/gohbase/blob/51c9c644410cad081633813d39a10cdba1c527e8/client.go#L559, it seems to me that if multiple goroutines are doing the same call, there's no guarantees that they'll receive the hrpc.Result associated with the hrpc.Mutate call.
* The parameters `rpcQueueSize` and `flushInterval` seems like it's there to batch up requests. Are there any tips to tweaking these numbers for high throughput? (I'm currently looking at 10k events/second from kafka--but this number will increase to roughly 200k/second)

Thanks for your time!

**Comment by tsuna** [comment]
Yeah the client is trying to be thread-safe.  If it's not, it's a bug.  I don't see any issue with the line you're referring to, can you clarify why you think that the `hrpc.Result` received would not be the one associated with the `hrpc.Mutate`?

For higher throughput, a longer queue / longer flush interval would be good, but that comes at the expense of higher latency and more RPC loss when the process gets killed uncleanly.  I don't have a good rule of thumb on how to set them for your use case, you'd have to experiment and see for yourself (please share results if you do!).

Please note that gohbase isn't considered v1 / stable yet.  There may still be API changes, and there are known and unknown bugs.  Please file issues / send pull requests if you want to help!

**Comment by Taik** [comment]
Hey tsuna, thanks for the quick response.

I might've misunderstood the code regarding point 1, my apologies!

The issue I was trying to track down was this:
![screen shot 2016-03-16 at 11 59 47 am](https://cloud.githubusercontent.com/assets/175499/13819107/b3070482-eb6e-11e5-925e-8643b093302c.png)
(Blue line: `runtime.MemStats.StackInuse`, Purple line: `runtime.MemStats.HeapAlloc` from https://golang.org/pkg/runtime/#MemStats)


It seems like the culprit at least in my case was a combination of:
* Not passing a timeout context (I was just passing `context.Background()`)
* Relying on the default `rpcQueueSize` (it seems like the default of 100 per 20ms was too low for our use case)

Tuning the `rpcQueueSize` to 10k per 20ms, as well as passing `context.WithTimeout(context.Background(), 30*time.Second)` seems to do the trick for me and the application is no longer crashing.

**Comment by caesarjuly** [comment]
Hi @Taik , thanks for ur sharing. I'm doing the same thing, consuming kafka events into hbase. At first I think the hbase put latency wiil be an issue. So I make a channel between my consumer and writing handler. Consumer is responsible for consuming events and handler is responsible for formatting and writing into hbase. Both of them are goroutines. But when running at production environment, the lag of kafka consumer offset is becoming larger and larger whatever I increase the handler count or not. I feel really confusing about this situation. Does this situation ring a bell?  What's ur architecture? 
Thank you!
