### ISSUE TITLE
!!! bug? scan the table, count of PartialFlagPerResult is not equal to CellsPerResult ?

### ISSUE THREAD

**Issue by lungfei** [tsuna/gohbase#81]
when scanner.Next() called, the client crash with error: index out of range
the reason is when i scan the table, the count of CellsPerResult is n (n>0), the count of PartialFlagPerResult is 0. but why the count of PartialFlagPerResult is 0?

**Comment by lungfei** [comment]
hrpc/scan.go  DeserializeCellBlocks() 239:
scanResp := m.(*pb.ScanResponse)
	partials := scanResp.GetPartialFlagPerResult()
	**partials = make([]bool, len(scanResp.CellsPerResult), len(scanResp.CellsPerResult))**
	scanResp.Results = make([]*pb.Result, len(partials))
make partials size is equal to CellsPerResult is ok, but i don't know true or false.

**Comment by lungfei** [comment]
sorry to reply late, HBase version is 1.2.

**Comment by WanliTian** [comment]
+1

**Comment by WanliTian** [comment]
i have found the reason why len(CellsPerResult) is not equal to len(PartifalFlagsPerResult)
https://blogs.apache.org/hbase/entry/scan_improvements_in_hbase_1

**Comment by WanliTian** [comment]
@lungfei  1.2 is ok

**Comment by Inphi** [comment]
Partial flags shouldn't be relied on as they aren't even transmitted by hbase server versions between 1.0.0 and 1.0.3.

**Comment by Inphi** [comment]
@lungfei I have a [branch](https://github.com/Inphi/gohbase/tree/issue-81) that addresses this issue. Please let me know if that works for you too.
