### ISSUE TITLE
github.com/tsuna/gohbase.a: no such file or directory

### ISSUE THREAD

**Issue by Shark4109** [tsuna/gohbase#82]
Hi, i"m trying to use this client, but i"m having some issues. As soon as i try to use it I get the following error:

```
# command-line-arguments
/home/..../go-1.9.2/pkg/tool/linux_amd64/link: cannot open file /home/..../go-1.9.2/pkg/linux_amd64/github.com/tsuna/gohbase.a: open /home/..../go-1.9.2/pkg/linux_amd64/github.com/tsuna/gohbase.a: no such file or directory
```

Real paths were obfuscate by .....

My import look like this 

```
import (
	"github.com/tsuna/gohbase"
)
```

package is located directly inside of folder which is set by GOPATH e.g.

GOPATH: "/home/example/workspaces/go"
Location of package: "/home/example/workspaces/go/github.com/tsuna/gohbase"

Any idea where the problem could be?

**Comment by jonbonazza** [comment]
Hi, when developing Go code, you need to place your projects under $GOPATH/src.

Thus, your project path should look like this:
```/home/example/workspaces/go/src/github.com/tsuna/gohbase```

Similarly, you'll also need the folders ```$GOPATH/bin``` and ```$GOPATH/pkg``` to exist.

**Comment by timoha** [comment]
Read [How to Write Go Code](https://golang.org/doc/code.html).
