### ISSUE TITLE
establishRegion memory leak

### ISSUE THREAD

**Issue by Taik** [tsuna/gohbase#9]
Hi there, just following up on the previous issue that I was having (memory leak). I was lucky enough this time to be able to take a pprof dump with `--inuse_objects` before the program crashed.

Here's the output of `top5 -cum`:

```
$ go tool pprof --inuse_objects aardvark_35de5ef_linux_amd64/event-persister $HOME/pprof/pprof.event-persister.__omitted__:6060.inuse_objects.inuse_space.024.pb.gz                                                                                                                           130 ↵
Entering interactive mode (type "help" for commands)
(pprof) top5 -cum
0 of 1932512 total (    0%)
Dropped 248 nodes (cum <= 9662)
Showing top 5 nodes out of 30 (cum >= 1389497)
      flat  flat%   sum%        cum   cum%
         0     0%     0%    1929781 99.86%  runtime.goexit
         0     0%     0%    1453748 75.23%  <...>/vendor/github.com/tsuna/gohbase.(*client).establishRegion
         0     0%     0%    1453748 75.23%  <...>/vendor/github.com/tsuna/gohbase.(*client).reestablishRegion
         0     0%     0%    1389497 71.90%  <...>/vendor/github.com/golang/protobuf/proto.(*Buffer).Unmarshal
         0     0%     0%    1389497 71.90%  <...>/vendor/github.com/golang/protobuf/proto.(*Buffer).unmarshalType
(pprof)
```

Here's the output from tracing down the object allocs: https://gist.github.com/Taik/0788d61dc48868c1aa98

Some related graphs:
![screen shot 2016-03-16 at 4 21 15 pm](https://cloud.githubusercontent.com/assets/175499/13827561/908efc78-eb93-11e5-95bd-643631c09b7a.png)
![screen shot 2016-03-16 at 4 21 03 pm](https://cloud.githubusercontent.com/assets/175499/13827562/947f012a-eb93-11e5-8430-1b6cba22af79.png)

If there's anything else you need, please let me know. I'd be willing to spend some cycles fixing this the upcoming few weeks if you don't have capacity.

Thanks!

**Comment by Preetam** [comment]
Hey @Taik, do you have any updates on this?

**Comment by Taik** [comment]
@Preetam no sorry, I haven't had time to actually visit this at $DAYJOB. I'm currently bypassing this by periodically restarting the service every N hours, which seems to work okay but is not ideal.

**Comment by Timoha** [comment]
Hello,
Are you still seeing the memory leak?
