### ISSUE TITLE
Logic Bug in scanner fetcher.fetch method

### ISSUE THREAD

**Issue by jonbonazza** [tsuna/gohbase#90]
I was investigating an issue we are seeing and came across the following conditional in scanner.go:
```go
resp, region, err := f.next()
if err != nil {
	if err != context.Canceled || err != context.DeadlineExceeded {
		// if the context of the scan rpc wasn't cancelled (same as calling Close()),
		// return the error to client
		f.trySend(nil, err)
	}
	break
}
```

I think that the inner coditional (regarding the context errors) should instead read:

```go
if err != context.Canceled && err != context.DeadlineExceeded {
	// if the context of the scan rpc wasn't cancelled (same as calling Close()),
	// return the error to client
	f.trySend(nil, err)
}
```

If you think about it, as it was originally (with the OR operator), if the fist part of the conditional, ```err != context.Canceled``` is ```false```, then that means that the error _is_ a context.Canceled error and  the second part of the conditional ```err!= context.DeadlineExceeded``` will always be ```true```.

I think what's trying to be accomplished here is making sure that the error is neither a Canceled or DeadlineExceeded error before we return the error to the client.

**Comment by timoha** [comment]
I've made a change (https://github.com/tsuna/gohbase/commit/774865576a9e5d9398d5328db6c30a29783794f3) to scanner to actually return any context related errors to the client instead of just returning io.EOF (it bit me as well). Let me know how it goes.
