### ISSUE TITLE
problem with "looking up region"

### ISSUE THREAD

**Issue by lanmanlanman** [tsuna/gohbase#96]
so it connects to the client. 
But I came across with a problem: 
-level=error msg="failed looking up region" backoff=16ms err="context deadline exceeded" key="\"row1\"" table="\"emp\"" 
and 
-level=error msg="failed looking up region" backoff=16ms err="context deadline exceeded" key="\"\"" table="\"hbase:meta\""

any idea how to solve this? thanks in advance

**Comment by chennqqi** [comment]
+1

**Comment by meission** [comment]
after split region,region info is not realtime .

**Comment by chzhuo** [comment]
```golang
import "github.com/sirupsen/logrus"
logrus.SetLevel("debug")
```
Open debug log and check details

**Comment by NginxL** [comment]
+1

**Comment by leecha** [comment]
add hbase hosts in local /ect/hosts

**Comment by sailsea** [comment]
+1

**Comment by knight-shade** [comment]
Still facing the same issue even after adding ip:hostname mapping.

**Comment by naserfuni** [comment]
I use remote zookeeper. Sets zookeepers address as input fix my issue.

**Comment by XieWeiXie** [comment]
Still facing the same issue even
